version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
        - "black"
        - "furo"
        - "isort"
        - "pre-commit"
        - "pyright"
        - "pytest-cov"
        - "pytest-image-diff"
        - "pytest"
        - "reportlab"
        - "sphinx_design"
        - "svglib"
        - "sybil"
  - package-ecosystem: "npm"
    directory: "/docs/try"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
        - "*"
