version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "flask"
          - "furo"
          - "pyright"
          - "pytest-cov"
          - "pytest-image-diff"
          - "pytest"
          - "PyYAML"
          - "reportlab"
          - "sphinx_design"
          - "sphinx-autobuild"
          - "sphinx-syntax"
          - "sphinx"
          - "svglib"
          - "sybil"
          - "tox"
      style:
        patterns:
          - "prek"
          - "ruff"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/docs/try"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "*"
