repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types_or: [python, pyi]
        require_serial: true
      - id: isort
        name: isort
        language: system
        entry: isort --filter-files
        types_or: [python, pyi]
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "^test/image_diff_reference/.*$"
      - id: end-of-file-fixer
        exclude: "^test/image_diff_reference/.*$"
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
